

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 09/02/2004 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>SADLA - Member Benefits</title>
<meta name="description" content="">
<meta name="keywords" content="">
<!-- start of header file -->

<script language="javascript" src="includes/default_javascript.js" type="text/javascript"></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<link href="/forum/includes/default_style.css" rel="stylesheet" type="text/css" />

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--jAVA FOR NAVE CELL COLOR CHANGE -->
<script language="Javascript"> 
	<!-- 
	function inCell(cell, newcolor) { 
		cell.bgColor = newcolor; 
	} 

	function outCell(cell, newcolor) { 
		cell.bgColor = newcolor;
	} 
	
	function go(loc) {
		window.location.href = loc;
	}
//  End -->
</script>


	<style>
		#popwindow { display: none;	}
	</style>


</head>


<!-- no popout -->
		<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#ffffff">

<table cellspacing="0" cellpadding="0" border="0" width="100%"><tr>
	<td width="136" style="background:#009cf0; margin:10px; padding-top:10px;" valign="top">
	<div align="center"><img src="/images/sadlaLogo.gif" width="82" height="135" border="0" alt=""></div>
		<br />
<div id=navvy>
<table class="tooltext1" cellspacing="0" cellpadding="0" style="border:0px;">
	<tr>

  
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('default.asp')" height="27"> 
  &nbsp;Home
  </TD></tr><tr>
	
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#999999" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#999999');" onclick="go('benefits.asp')" height="27"> 
  &nbsp;Membership&nbsp;Benefits
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('events.asp')" height="27"> 
  &nbsp;Events
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('links.asp')" height="27"> 
  &nbsp;Links
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('constitution.asp')" height="27"> 
	&nbsp;Constitution
	</TD></tr><tr>
	
<!-- 	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('news.asp')" height="27"> 
	&nbsp;News
	</TD></tr><tr> -->
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/members/member-home.asp')" height="27"> 
  &nbsp;Member Area
  </TD></tr><tr>
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/forum/')" height="27"> 
  &nbsp;Forum
  </TD></tr><tr>
  
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('join.asp')" height="27"> 
  &nbsp;Join
  </TD></tr><tr>	
			
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('contact.asp')" height="27"> 
  &nbsp;Contact&nbsp;us
	</TD></tr><tr>
		
	<!-- closing cell -->
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#009cf0" WIDTH="153" height="27">&nbsp;
	
	</TD></tr>
  </table>
</div>  <!-- end of navvy -->	 
<!-- End of menu table -->

</td>
	<td valign="top">
	
	<!-- its a table to just hold the banner -->
		<table width="100%" border="0" cellspacing="0" cellpadding="0" height="30">
      <tr bgcolor="#009CF0">
       	  <td height="30"> 
         	  <div align="center"><img src="/Images/slogan2.gif" width="486" height="25"
           	alt="Sheffield District and Landlord Association" align="middle"> </div>
         	</td>
      </tr>
    </table>
		
			<img src="../images/corner.gif" width="25" height="20" border="0" alt="">	
			
<!-- end of header file -->

      <table width="95%" border="0" cellspacing="0" cellpadding="10">
        <tr> 
          <td width="1%">&nbsp;</td>
          <td> 
            <p class="title">Membership Benefits</p>
            <p><span class="subtitle">Discounts</span></p>
            <blockquote> 
              <p> Take advantage of the Association's group buying power to access 
                cheap <a href="members/discounts.asp">buildings insurance</a>, <a href="members/discounts.asp#trade">trade 
                discounts</a>, and exclusive deals on <a href="members/discounts.asp#finance">finance</a>, 
                <a href="members/discounts.asp#web">website 
                design</a> and more. 
              </p>
            </blockquote>
            <p> <span class="subtitle">Information</span></p>
            <blockquote> 
              <p> Keep informed of the latest legislation through regular network 
                meetings and advice forums, and a quarterly magazine from the 
                <a href="http://www.landlords.org.uk/" target="_blank">National Landlords Association
                </a>.&nbsp;<img src="/images/exlink.gif"></p>
            </blockquote>
            <p><span class="subtitle">Free Advertising/Advice</span></p>
            <blockquote> 
              <p> Use our <strong>Forum</strong> to advertise a 
                property for sale or rent, to request advice from other landlords 
                on any property issue, or to publicise a relevant event. </p>
            </blockquote>
            <p><span class="subtitle">Networking</span></p>
            <blockquote> 
              <p> Be part of a large body of landlords across the city. As part 
                of a large association, get your voice heard, help raise the image 
                of the profession and share advice and experience. </p>
            </blockquote>
            <p>Please see the <a href="join.asp">join</a> page for further information 
              about becoming a member of SADLA.</p>
          </td>
        </tr>
      </table>

<!-- footer -->

	<table width="95%"><tr>
 		<td valign="middle" bgcolor="#FFFFFF" height="30"><div align="center" class="copyright">Copyright
    	© 2002 Sheffield and District Landlord Association  |  Site by <a
    	href="http://www.novate.co.uk" target="_blank" class="subtitle">Novate</a>
    	</div></td>
  	</tr>
	</table>
</table>
</body>
</html>