

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 09/02/2004 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>SADLA - Constitution</title>
<meta name="description" content="">
<meta name="keywords" content="">
<!-- start of header file -->

<script language="javascript" src="includes/default_javascript.js" type="text/javascript"></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<link href="/forum/includes/default_style.css" rel="stylesheet" type="text/css" />

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--jAVA FOR NAVE CELL COLOR CHANGE -->
<script language="Javascript"> 
	<!-- 
	function inCell(cell, newcolor) { 
		cell.bgColor = newcolor; 
	} 

	function outCell(cell, newcolor) { 
		cell.bgColor = newcolor;
	} 
	
	function go(loc) {
		window.location.href = loc;
	}
//  End -->
</script>


	<style>
		#popwindow { display: none;	}
	</style>


</head>


<!-- no popout -->
		<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#ffffff">

<table cellspacing="0" cellpadding="0" border="0" width="100%"><tr>
	<td width="136" style="background:#009cf0; margin:10px; padding-top:10px;" valign="top">
	<div align="center"><img src="/images/sadlaLogo.gif" width="82" height="135" border="0" alt=""></div>
		<br />
<div id=navvy>
<table class="tooltext1" cellspacing="0" cellpadding="0" style="border:0px;">
	<tr>

  
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('default.asp')" height="27"> 
  &nbsp;Home
  </TD></tr><tr>
	
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('benefits.asp')" height="27"> 
  &nbsp;Membership&nbsp;Benefits
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('events.asp')" height="27"> 
  &nbsp;Events
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('links.asp')" height="27"> 
  &nbsp;Links
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#999999" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#999999');" onclick="go('constitution.asp')" height="27"> 
	&nbsp;Constitution
	</TD></tr><tr>
	
<!-- 	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('news.asp')" height="27"> 
	&nbsp;News
	</TD></tr><tr> -->
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/members/member-home.asp')" height="27"> 
  &nbsp;Member Area
  </TD></tr><tr>
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/forum/')" height="27"> 
  &nbsp;Forum
  </TD></tr><tr>
  
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('join.asp')" height="27"> 
  &nbsp;Join
  </TD></tr><tr>	
			
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('contact.asp')" height="27"> 
  &nbsp;Contact&nbsp;us
	</TD></tr><tr>
		
	<!-- closing cell -->
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#009cf0" WIDTH="153" height="27">&nbsp;
	
	</TD></tr>
  </table>
</div>  <!-- end of navvy -->	 
<!-- End of menu table -->

</td>
	<td valign="top">
	
	<!-- its a table to just hold the banner -->
		<table width="100%" border="0" cellspacing="0" cellpadding="0" height="30">
      <tr bgcolor="#009CF0">
       	  <td height="30"> 
         	  <div align="center"><img src="/Images/slogan2.gif" width="486" height="25"
           	alt="Sheffield District and Landlord Association" align="middle"> </div>
         	</td>
      </tr>
    </table>
		
			<img src="../images/corner.gif" width="25" height="20" border="0" alt="">	
			
<!-- end of header file -->

<table width="95%" border="0" cellspacing="0" cellpadding="10">
        <tr> 
          <td width="1%">&nbsp;</td>
          <td valign="top" colspan="3"> 
            <p class="title"> Constitution <br>
            </p>
            <table width="85%" border="0" cellpadding="3">
              <tr> 
                <td width="5%" class="subtitle" valign="top">1.</td>
                <td width="95%" valign="top"> 
                  <center>
                  </center>
                  <span class="subtitle"><basefont size=2>Name</span><br>
                  The name of the Association is "Sheffield and District Landlord 
                  Association" (Hereinafter called The Association) </td>
              </tr>
              <tr> 
                <td width="5%" class="subtitle" valign="top" height="212">2.</td>
                <td width="95%" valign="top" height="212"> 
                  <center>
                  </center>
                  <span class="subtitle">Objectives of The Association</span><br>
                  The Association exists to promote and represent Landlords who 
                  let properties. In furtherance of the objectives The Association 
                  may:<br>
                  <ul>
                    <li> Work in partnership with Local Councils and other relevant 
                      bodies to promote the trade of Sheffield Landlord via regular 
                      meetings with interested Statutory Services Groups</li>
                    <li> Provide a steering group for the consideration of matters 
                      relatimg to the letting of properties</li>
                    <li>Liaise with other relevant Associations</li>
                    <li>Present the views of the Members to Local Authorities 
                      and other relevant bodies.</li>
                    <li>Promote such activities as may benefit the Members and 
                      safeguard their interests</li>
                    <li>Promote and carry out research, surveys and investigations 
                      via the steering group</li>
                    <li>Promote and encourage Good Practice </li>
                  </ul>
                </td>
              </tr>
              <tr> 
                <td width="5%" class="subtitle" valign="top">3.</td>
                <td width="95%" valign="top"> <p><span class="subtitle">Executive 
                    Committee (Hereinafter called The Committee)<br>
                    </span>The Committee shall direct policy and the general mangement 
                    of the affairs of The Association. </p>
                  <ul>
                    <li>The Committee shall direct policy and the general management 
                      of the affairs of The Association.</li>
                    <li> The Members of The Committee shall be elected at the 
                      A.G.M for the following year. The proceedings of The Committee 
                      shall not be invalidated by the failure to elect a Member
                    <li>Any Committee Officer not attending 3 consecutive meetings without leave of 
                      absence will be removed from Officer status, subject to 
                      the discretion of the Committee
                    <li>The Committee shall meet to discuss relevant matters and make recommendations 
                      to the Members as appropriate
                    <li>The Committee shall issue interesting items of concern via the Minutes secretary
<li>Only full members of the association whose subscription 
                      fee is fully paid up to date may apply for committee nomination 
                      or retain a place on the committee.<br>
                    </li>
                  </ul></td>
              </tr>
              <tr> 
                <td width="5%" class="subtitle" valign="top">4.</td>
                <td width="95%" valign="top"><span class="subtitle">Officers of 
                  Executive Committee</span> <br>
                  The Committee shall consist of the following Officers: 
                  <ul>
                    <li>The Chairman - who will control all meetings (and if absent 
                      the Vice Chair) 
                    <li>Two Vice-Chairpersons 
                    <li>The Treasurere - who will make payments, maintain proper 
                      records of receipts and generally safeguard the funds of 
                      The Association. He will present the annual accounts to 
                      the AGM 
                    <li>A Membership Secretary who will be responsible for all 
                      membership/application issues 
                    <li>A General Secretary responsible for correspondence 
                    <li>The Secretary - who will be responsible for correspondance 
                      and arrange for the Minute Taker 
                    <li>Publicity Officer 
                    <li>Website/IT Officer 
                    <li>Other Committee Members - responsible for such functions 
                      as delegated to them </ul>
                </td>
              </tr>
              <tr> 
                <td width="5%" class="subtitle" valign="top">5.</td>
                <td width="95%" valign="top"> <span class="subtitle">Membership</span><br>
                  Full membership of The Association shall be open to Landlords 
                  who:<br>
                  <ul>
                    <li>Let property for residential (and commercial) purposes 
                    <li>Agree to adopt and comply with the Constitution and the 
                      Code of Practice </li>
                    <li>Have paid the annual subscription as laid down in this 
                      Constitution 
                  </ul>
                  <p>Managing Agents and other persons with a legitimate interest 
                    in residential property may also be admitted ot Associate 
                    Non-Voting Membership at the discretion of The Committee. 
                  </p>
                </td>
              </tr>
              <tr> 
                <td width="5%" class="subtitle" valign="top">6.</td>
                <td width="95%" valign="top"> <span class="subtitle">Discipline 
                  Code<br>
                  </span> If it is the opinion of The Committee that some action 
                  or omission by a member has resulted in the bringing of disrepute 
                  upon The Association, then dismissal from the Association will 
                  take place. The Member concerned shall have the right to appeal 
                  to the Members voting in the following open meeting; or may, 
                  with the support of three Members, ask for an EGM </td>
              </tr>
              <tr> 
                <td width="5%" class="subtitle" valign="top">7.</td>
                <td width="95%" valign="top"> 
                  <p><span class="subtitle">Financial Aspects<br>
                    a. </span>The financial year of The Association starts on 
                    1st April and ends on the 31st March. The Committee shall 
                    comply with their obligations to: </p>
                  <ul>
                    <li>Keep accurate accounting records of The Association </li>
                    <li>Submit the financial statements to the AGM<br>
                    </li>
                  </ul>
                  <p><span class="subtitle">b. </span>Payments - all monies raised 
                    by donations and receipts on behalf of The Association shall 
                    be applied to further the objectives of The Association and 
                    for no other purpose provided that nothing herein contained 
                    shall prevent the repayment to <span class="subtitle">c. </span>Members 
                    of The Committee of reasonable out-of-pocket expenses.<br>
                    <br>
                    Subscriptions</p>
                  <ul>
                    <li>All Members, unless exempt, shall pay their subscriptions 
                      by the due date.</li>
                    <li>The Committee will consider exemptions on a case by case 
                      basis </li>
                    <li>New Members will pay the full annual subscription.</li>
                    <li>The amount of subscription may vary from time to time, 
                      being determined by The Committee and approved at an A.G.M 
                      or EGM</li>
                    <li> Membership can terminate for any Member whose subscription 
                      is three calendar months in arrears </li>
                  </ul>
                </td>
              </tr>
              <tr> 
                <td width="5%" class="subtitle" valign="top">8.</td>
                <td width="95%" valign="top"> <span class="subtitle">Annual General 
                  Meeting (hereinafter called AGM)</span><br>
                  The AGM of The Association shall be held in the month of May 
                  at a suitable venue. The business shall include the election 
                  of Committee Members and the presentation of the financial statements 
                  and to vote on constitution changes and members proposals. 
                  </td>
              </tr>
              <tr> 
                <td width="5%" class="subtitle" valign="top" height="82">9.</td>
                <td width="95%" valign="top" height="82"> <span class="subtitle">Extraordinary 
                  General Meeting(hereinafter called EGM)</span><br>
                  An EGM may be called by not less than three Members to deal 
                  with a matter of great importance. Unless The Committee considers 
                  the matter to be trivial or adequately dealt with elsewhere, 
                  they must convene such a meeting giving a minimum of three weeks' 
                  notice.</td>
              </tr>
              <tr> 
                <td width="5%" class="subtitle" valign="top">10.</td>
                <td width="95%" valign="top"><span class="subtitle">General Meetings<br>
                  </span> There shall be one meeting approximately every quarter, 
                  with other meetings as required. The business may include reports 
                  of Activities, presentations by guest speakers and discussion 
                  of matters of concern. </td>
              </tr>
              <tr> 
                <td width="5%" class="subtitle" valign="top">11.</td>
                <td width="95%" valign="top"><span class="subtitle">Committee 
                  Meetings<br>
                  </span> The Committee shall meet to discuss Activities or Matters 
                  of Concern. These will be known as "Steering Group" meetings, 
                  and can allow non-committee members to attend and express 
                  opinions but not vote. </td>
              </tr>
              <tr> 
                <td width="5%" class="subtitle" valign="top">12.</td>
                <td width="95%" valign="top"><span class="subtitle">Amendments<br>
                  </span> Amendments to the Constitution or Code of Practice of 
                  The Association may only take place at the AGM (or EGM if specially 
                  requested for this purpose). </td>
              </tr>
              <tr> 
                <td width="5%" class="subtitle" valign="top">13.</td>
                <td width="95%" valign="top"><span class="subtitle">Members' Rules, 
                  Procedures and Voting </span> 
                  <ul>
                    <li>Members will be given adequate notice of the time and 
                      place of meetings 
                    <li>A Quorum shall consist of four Members entitled to vot 
                    <li>All matters will be decided by a simple majority of those 
                      attending and entitled to vote 
                    <li>A record of all proceedings and resolutions shall be minuted/recorded 
                      by an appopriate Member of The Committee, or a Co-opted 
                      Association Member. 
                  </ul>
                </td>
              </tr>
              <tr> 
                <td colspan="2" valign="top"> 
                  <div align="center"><a href="#top">Top</a></div>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
<!-- footer -->

	<table width="95%"><tr>
 		<td valign="middle" bgcolor="#FFFFFF" height="30"><div align="center" class="copyright">Copyright
    	© 2002 Sheffield and District Landlord Association  |  Site by <a
    	href="http://www.novate.co.uk" target="_blank" class="subtitle">Novate</a>
    	</div></td>
  	</tr>
	</table>
</table>
</body>
</html>