

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 09/02/2004 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>SADLA - Contact Sadla</title>
<meta name="description" content="">
<meta name="keywords" content="">
<!-- start of header file -->

<script language="javascript" src="includes/default_javascript.js" type="text/javascript"></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<link href="/forum/includes/default_style.css" rel="stylesheet" type="text/css" />

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--jAVA FOR NAVE CELL COLOR CHANGE -->
<script language="Javascript"> 
	<!-- 
	function inCell(cell, newcolor) { 
		cell.bgColor = newcolor; 
	} 

	function outCell(cell, newcolor) { 
		cell.bgColor = newcolor;
	} 
	
	function go(loc) {
		window.location.href = loc;
	}
//  End -->
</script>


	<style>
		#popwindow { display: none;	}
	</style>


</head>


<!-- no popout -->
		<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#ffffff">

<table cellspacing="0" cellpadding="0" border="0" width="100%"><tr>
	<td width="136" style="background:#009cf0; margin:10px; padding-top:10px;" valign="top">
	<div align="center"><img src="/images/sadlaLogo.gif" width="82" height="135" border="0" alt=""></div>
		<br />
<div id=navvy>
<table class="tooltext1" cellspacing="0" cellpadding="0" style="border:0px;">
	<tr>

  
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('default.asp')" height="27"> 
  &nbsp;Home
  </TD></tr><tr>
	
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('benefits.asp')" height="27"> 
  &nbsp;Membership&nbsp;Benefits
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('events.asp')" height="27"> 
  &nbsp;Events
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('links.asp')" height="27"> 
  &nbsp;Links
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('constitution.asp')" height="27"> 
	&nbsp;Constitution
	</TD></tr><tr>
	
<!-- 	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('news.asp')" height="27"> 
	&nbsp;News
	</TD></tr><tr> -->
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/members/member-home.asp')" height="27"> 
  &nbsp;Member Area
  </TD></tr><tr>
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/forum/')" height="27"> 
  &nbsp;Forum
  </TD></tr><tr>
  
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('join.asp')" height="27"> 
  &nbsp;Join
  </TD></tr><tr>	
			
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#999999" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#999999');" onclick="go('contact.asp')" height="27"> 
  &nbsp;Contact&nbsp;us
	</TD></tr><tr>
		
	<!-- closing cell -->
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#009cf0" WIDTH="153" height="27">&nbsp;
	
	</TD></tr>
  </table>
</div>  <!-- end of navvy -->	 
<!-- End of menu table -->

</td>
	<td valign="top">
	
	<!-- its a table to just hold the banner -->
		<table width="100%" border="0" cellspacing="0" cellpadding="0" height="30">
      <tr bgcolor="#009CF0">
       	  <td height="30"> 
         	  <div align="center"><img src="/Images/slogan2.gif" width="486" height="25"
           	alt="Sheffield District and Landlord Association" align="middle"> </div>
         	</td>
      </tr>
    </table>
		
			<img src="../images/corner.gif" width="25" height="20" border="0" alt="">	
			
<!-- end of header file -->

      <table width="95%" border="0" cellspacing="0" cellpadding="10">
        <tr> 
          <td width="1%">&nbsp;</td>
          <td valign="top" colspan="3"> 
            <p class="title"> Contact Us</p>
            <p> Please click <a href="members/committee.asp">here</a>&nbsp;<img src="/images/padlock.gif">&nbsp;for a list of committee 
              members. </p>
            <p>Please click <a href="members/member-list.asp">here</a>&nbsp;<img src="/images/padlock.gif">&nbsp;for a list of SADLA 
              members.<br>
              <br>
              For general information, please contact: </p>
            <blockquote>
              <p>Mr Stuart Simcock<br>
                Secretary <br>
                SADLA <br>
                PO Box 3199 <br>
                Sheffield <br>
                S11 7WR <br>
                <br>
                <span class="subtitle">Tel/Fax</span> : 0114 2960670<br>
                <br>
                <span class="subtitle">Email</span>: 
				<script type="text/javascript">
				
				/***********************************************
				* Encrypt Email script- Please keep notice intact.
				* Tool URL: http://www.dynamicdrive.com/emailriddler/
				* **********************************************/
				
				var emailarray7242= new Array(105,110,102,111,64,115,97,100,108,97,46,111,114,103,46,117,107)
				var postemail7242=''
				for (i=0;i<emailarray7242.length;i++)
				postemail7242+=String.fromCharCode(emailarray7242[i])
				
				document.write('<a href="mailto:'+postemail7242+'?subject=Sadla Website enquiry">'+postemail7242+'</a>')
				
				</script>
				</p>
            </blockquote>
          </td>
        </tr>
      </table>

<!-- footer -->

	<table width="95%"><tr>
 		<td valign="middle" bgcolor="#FFFFFF" height="30"><div align="center" class="copyright">Copyright
    	© 2002 Sheffield and District Landlord Association  |  Site by <a
    	href="http://www.novate.co.uk" target="_blank" class="subtitle">Novate</a>
    	</div></td>
  	</tr>
	</table>
</table>
</body>
</html>