

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 09/02/2004 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>SADLA - News</title>
<meta name="description" content="">
<meta name="keywords" content="">
<!-- start of header file -->

<script language="javascript" src="includes/default_javascript.js" type="text/javascript"></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<link href="/forum/includes/default_style.css" rel="stylesheet" type="text/css" />

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--jAVA FOR NAVE CELL COLOR CHANGE -->
<script language="Javascript"> 
	<!-- 
	function inCell(cell, newcolor) { 
		if (!cell.contains(event.fromElement)) { 
		cell.bgColor = newcolor; 
		} 
	} 

	function outCell(cell, newcolor) { 
		if (!cell.contains(event.toElement)) { 
		cell.bgColor = newcolor;
		} 
	} 
	
	function go(loc) {
		window.location.href = loc;
	}
//  End -->
</script>


	<style>
	<!-- Start of tags for the pop-out advert - when not enabled -->
	#winDisplay {
	 display: none;
	}
	</style>


</head>


<!-- no popout -->
		<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#ffffff">

<table cellspacing="0" cellpadding="0" border="0" width="100%"><tr>
	<td width="136" style="background:#009cf0; margin:10px; padding-top:10px;" valign="top">
	<div align="center"><img src="/images/sadlaLogo.gif" width="82" height="135" border="0" alt=""></div>
		<br />
<div id=navvy>
<table class="tooltext1" cellspacing="0" cellpadding="0" style="border:0px;">
	<tr>

  
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('default.asp')" height="27"> 
  &nbsp;Home
  </TD></tr><tr>
	
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('benefits.asp')" height="27"> 
  &nbsp;Membership&nbsp;Benefits
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('events.asp')" height="27"> 
  &nbsp;Events
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('links.asp')" height="27"> 
  &nbsp;Links
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('constitution.asp')" height="27"> 
	&nbsp;Constitution
	</TD></tr><tr>
	
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('news.asp')" height="27"> 
	&nbsp;News
	</TD></tr><tr>
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/members/member-home.asp')" height="27"> 
  &nbsp;Member Area
  </TD></tr><tr>
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/forum/')" height="27"> 
  &nbsp;Forum
  </TD></tr><tr>
  
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('join.asp')" height="27"> 
  &nbsp;Join
  </TD></tr><tr>	
			
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('contact.asp')" height="27"> 
  &nbsp;Contact&nbsp;us
	</TD></tr><tr>
		
	<!-- closing cell -->
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#009cf0" WIDTH="153" height="27">&nbsp;
	
	</TD></tr>
  </table>
</div>  <!-- end of navvy -->	 
<!-- End of menu table -->

</td>
	<td valign="top">
	
	<!-- its a table to just hold the banner -->
		<table width="100%" border="0" cellspacing="0" cellpadding="0" height="30">
      <tr bgcolor="#009CF0">
       	  <td height="30"> 
         	  <div align="center"><img src="/Images/slogan2.gif" width="486" height="25"
           	alt="Sheffield District and Landlord Association" align="middle"> </div>
         	</td>
      </tr>
    </table>
		
			<img src="../images/corner.gif" width="25" height="20" border="0" alt="">	
			
<!-- end of header file -->

<table width="95%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td>&nbsp;</td>
          <td width="200" class="subtitle">&nbsp;</td>
        </tr>
        <tr> 
          <td><table width="100%" border="0" cellspacing="0" cellpadding="10">
              <tr>
                <td width="1%">&nbsp;</td>
                <td><h2 class="title">Special Housing Act-Legal Update Course 
                    Wednesday, 9th.November, 2005, at the Niagara Sports &amp; 
                    Social Club, 9.30-3.15</h2></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="text"><div align="left">
                    <p>Sadla have designed a course to brief you on the Legal 
                      aspects of the new Housing Act. This should give you all 
                      the information you need, including how some aspects of 
                      the act work to your advantage! Make sure you keep on the 
                      right side of the law&#8230;..</p>
                    <p>Topics to be included:</p>
                    <p>Housing Health &amp; Safety Rating Scheme<br>
                      Mandatory HMO Licensing<br>
                      Selective Licensing<br>
                      Additional Control Procedures<br>
                      Mandatory Tenancy Deposit Schemes<br>
                      Residential Property Tribunals<br>
                      Home Information Packs.<br>
                      <br>
                      This course would provide over 4 hours towards Continuous 
                      Professional Development Requirements For 2005 for any professional 
                      body who attends the day.</p>
                    <p> We hope to produce a CDRom containing an electronic, searchable 
                      copy of the vital material you need to have at your fingertips. 
                      It is hoped that you will receive your CDRom with your printed 
                      notes at the course.</p>
                    <p> Your bonus CD contains:</p>
                    <p>The Complete Housing Act 2004- all 332 pages of it.<br>
                      10 Fact Sheets-that summarise important aspects of the Housing 
                      Act<br>
                      An electronic, searchable version of the course.</p>
                    <p>The course has been extended to include invitations to 
                      Letting Agents, Solicitors &amp; Surveyors. The SADLA Committee 
                      are putting on this course at no charge to any SADLA Member 
                      but are levying a fee of &pound;75.00 to any non-SADLA Members 
                      who wish to attend the event.</p>
                    <p>The SADLA Committee are anticipating that the event will 
                      prove very popular &amp; may be oversubscribed so early 
                      application is essential to secure a place! Places will 
                      be reserved on a first apply basis, as numbers are limited, 
                      &amp; they are aware that there will be some SADLA Members 
                      who may not be able to attend a full day meeting or are 
                      not successful in securing a place owing to oversubscription. 
                      If the course is oversubscribed etc., then the SADLA Committee 
                      intend to put on an evening meeting on Wednesday, 8th.February, 
                      2006 to be held at Abbeydale Sports Club, Abbeydale Road 
                      South, Dore, Sheffield.S17 3LJ, for anyone who is either 
                      unsuccessful in reserving a place or who cannot attend the 
                      above course.</p>
                    <p>Refreshments &amp; a buffet lunch will be provided on the 
                      day &amp; the SADLA Committee look forward to meeting you 
                      again at what should be a very interesting event.</p>
                    <p>&nbsp;</p>
                  </div>
                  </td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
            </table></td>
          <td width="200" valign="top"><p><a href="RESERVATION%20CERTIFICATE.doc">Down 
              Load the Reservation Certificate</a></p>
            <p><a href="Course_Agenda.doc">Down Load 
              the Agenda</a></p>
            </td>
        </tr>
      </table>

<!-- footer -->

	<table width="95%"><tr>
 		<td valign="middle" bgcolor="#FFFFFF" height="30"><div align="center" class="copyright">Copyright
    	© 2002 Sheffield and District Landlord Association  |  Site by <a
    	href="http://www.novate.co.uk" target="_blank" class="subtitle">Novate</a>
    	</div></td>
  	</tr>
	</table>
</table>
</body>
</html>