

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 09/02/2004 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>SADLA - Sheffield and District Landlords Association</title>
<meta name="description" content="">
<meta name="keywords" content="">
<meta http-equiv="Cache-Control" content="No-cache">
<meta http-equiv="Expires" content="-1">
<meta http-equiv="Pragma" content="no-cache">

<!-- start of header file -->

<script language="javascript" src="includes/default_javascript.js" type="text/javascript"></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<link href="/forum/includes/default_style.css" rel="stylesheet" type="text/css" />

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--jAVA FOR NAVE CELL COLOR CHANGE -->
<script language="Javascript"> 
	<!-- 
	function inCell(cell, newcolor) { 
		cell.bgColor = newcolor; 
	} 

	function outCell(cell, newcolor) { 
		cell.bgColor = newcolor;
	} 
	
	function go(loc) {
		window.location.href = loc;
	}
//  End -->
</script>


	<style>
		#popwindow { display: none;	}
	</style>


</head>


<!-- no popout -->
		<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#ffffff">

<table cellspacing="0" cellpadding="0" border="0" width="100%"><tr>
	<td width="136" style="background:#009cf0; margin:10px; padding-top:10px;" valign="top">
	<div align="center"><img src="/images/sadlaLogo.gif" width="82" height="135" border="0" alt=""></div>
		<br />
<div id=navvy>
<table class="tooltext1" cellspacing="0" cellpadding="0" style="border:0px;">
	<tr>

  
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#999999" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#999999');" onclick="go('default.asp')" height="27"> 
  &nbsp;Home
  </TD></tr><tr>
	
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('benefits.asp')" height="27"> 
  &nbsp;Membership&nbsp;Benefits
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('events.asp')" height="27"> 
  &nbsp;Events
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('links.asp')" height="27"> 
  &nbsp;Links
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('constitution.asp')" height="27"> 
	&nbsp;Constitution
	</TD></tr><tr>
	
<!-- 	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('news.asp')" height="27"> 
	&nbsp;News
	</TD></tr><tr> -->
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/members/member-home.asp')" height="27"> 
  &nbsp;Member Area
  </TD></tr><tr>
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/forum/')" height="27"> 
  &nbsp;Forum
  </TD></tr><tr>
  
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('join.asp')" height="27"> 
  &nbsp;Join
  </TD></tr><tr>	
			
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('contact.asp')" height="27"> 
  &nbsp;Contact&nbsp;us
	</TD></tr><tr>
		
	<!-- closing cell -->
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#009cf0" WIDTH="153" height="27">&nbsp;
	
	</TD></tr>
  </table>
</div>  <!-- end of navvy -->	 
<!-- End of menu table -->

</td>
	<td valign="top">
	
	<!-- its a table to just hold the banner -->
		<table width="100%" border="0" cellspacing="0" cellpadding="0" height="30">
      <tr bgcolor="#009CF0">
       	  <td height="30"> 
         	  <div align="center"><img src="/Images/slogan2.gif" width="486" height="25"
           	alt="Sheffield District and Landlord Association" align="middle"> </div>
         	</td>
      </tr>
    </table>
		
			<img src="../images/corner.gif" width="25" height="20" border="0" alt="">	
			
<!-- end of header file -->

<div style="text-align:center; margin:auto;">
	<table width="95%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td valign=top style=" padding:5px;padding-right:20px;"><!-- Intro + News -->
				<h1>Welcome</h1>
				<p>Sheffield and District Landlord Association (SADLA) is
				 a non-profit making organisation of private landlords providing a united front to represent their interests.</p>
				<p>SADLA are affiliated to the <a href="http://www.landlords.org.uk/"
        			target="_blank">National Landlords Association</a>&nbsp;<img src="/images/exlink.gif">&nbsp; (NLA). 
                  	This is the only nationally recognised body of residential landlords 
                  	which is consulted by the Government, Judiciary and Media.</p>
				<p>Our <a href="benefits.asp">membership</a> covers all types 
                  	of landlord no matter how large or small their portfolio. <a href="join.asp">Join</a> 
                  	SADLA and help develop the Association in a way that can benefit 
                  	your business. </p>

				<h2 style="border-top:1px solid; border-bottom: 1px dotted; padding:10px 0px;">SADLA News</h2>
					<a name="news"></a> <div class="newsitem"><h2>With great sadness we have to announce the death of Stuart Simcock our treasurer and secretary
		</h2>
		

<p>Stuart Simcock passed away very suddenly&nbsp;last night. He was both&nbsp;the secretary and Treasurer of the association, and the committee will miss him dearly. Stuart has dedicated his semi retirement to the work of the association and&nbsp;we have all&nbsp;appreciated the tremendous contribution he has made.</p><p style="text-align:right"><a href="newsitem.asp?id=64&f=/default.asp">Read More...</a></p></div>  <div class="newsitem"><h2>
			<span style="float:right;color:#888; font-size:70%;">05/04/2009</span>
		Gas Safe Register is the new hallmark for gas safety in Great Britain. From April 1st 2009, Gas Safe Register replaces CORGI gas registration as the official gas safety body
		</h2>
		

<p><span style="FONT-SIZE: 10pt; FONT-FAMILY: 'Arial','sans-serif'">To help raise awareness within the letting industry please find<span style="FONT-SIZE: 10pt; mso-spacerun: yes">&nbsp; </span>provided some useful information taken from the Gas Safe Register website.&nbsp; </span></p><p style="text-align:right"><a href="newsitem.asp?id=62&f=/default.asp">Read More...</a></p></div>  <div class="newsitem"><h2>
			<span style="float:right;color:#888; font-size:70%;">05/08/2008</span>
		When is an EPC not required
		</h2>
		

<p>An EPC is only required for habital units which are self contained. If the&nbsp;tenant has a contract with a landlord for the parts of a property they have access to, but not as a whole dwelling then an EPC is not required. This is spelled out in a document recently published by the CLG June 2008. The page referenced by the above are on page 16.</p><p style="text-align:right"><a href="newsitem.asp?id=50&f=/default.asp">Read More...</a></p></div>  <div class="newsitem"><h2>
			<span style="float:right;color:#888; font-size:70%;">09/04/2008</span>
		Cannabis Factories within Rental Properties in Sheffield
		</h2>
		

<p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt 18pt; TEXT-INDENT: -18pt; tab-stops: list 18.0pt; mso-list: l0 level1 lfo1"><span lang="EN-GB" style="FONT-SIZE: 10pt; FONT-FAMILY: Arial; mso-bidi-font-size: 10.0pt">Over the last 18 months South Yorkshire Police have recovered well over &pound;6,000,000 worth of Cannabis cultivated within student type landlord owned properties. (20,000 mature plants) </span></p><p style="text-align:right"><a href="newsitem.asp?id=47&f=/default.asp">Read More...</a></p></div>  <div class="newsitem"><h2>
			<span style="float:right;color:#888; font-size:70%;">16/03/2008</span>
		Energy Performance Reports
		</h2>
		

<h1 style="MARGIN: 0cm 0cm 0pt"><span lang="EN-GB" style="FONT-SIZE: 10pt; FONT-FAMILY: Verdana">&nbsp;</span></h1>

<p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt"><span lang="EN-GB" style="FONT-SIZE: 10pt; FONT-FAMILY: Verdana; mso-ansi-language: EN-GB">
		<o:p></o:p>
		
<p class="MsoNormal" style="MARGIN: 0cm 0cm 0pt"><span lang="EN-GB" style="FONT-SIZE: 10pt; FONT-FAMILY: Verdana; mso-ansi-language: EN-GB">From October 2008 all rental properties in </span>
			<st1:country-region>
				<st1:place><span lang="EN-GB" style="FONT-SIZE: 10pt; FONT-FAMILY: Verdana; mso-ansi-language: EN-GB">England</span></st1:place></st1:country-region><span lang="EN-GB" style="FONT-SIZE: 10pt; FONT-FAMILY: Verdana; mso-ansi-language: EN-GB"> and </span>
			<st1:country-region>
				<st1:place><span lang="EN-GB" style="FONT-SIZE: 10pt; FONT-FAMILY: Verdana; mso-ansi-language: EN-GB">Wales</span></st1:place></st1:country-region><span lang="EN-GB" style="FONT-SIZE: 10pt; FONT-FAMILY: Verdana; mso-ansi-language: EN-GB"> will be required to have an Energy Performance Certificate (EPC) prepared by an accredited Energy Assessor. These will offer opportunities for landlords to differentiate their property from their competitors and gain a distinct marketing advantage. 
				<o:p></o:p></span></p><p style="text-align:right"><a href="newsitem.asp?id=46&f=/default.asp">Read More...</a></p></div> 
	
	<span style="float:right;"><a href="/news/login.asp?from=/default.asp#news" style="text-decoration:none; color:gray;">edit</a></span>
	
	

			</td>
			<td valign=top width="220px" style="background-color:#e6f7ff; border:1px solid #c0c0c0; padding:5px;"><!-- Events -->
				<h2 class="title">Upcoming Events</h2><hr />
				<a name="events"></a> <div class="eventitem"><h3 ><img src="/images/calendar.png" />
	&nbsp;10/11/2009 - Sadla Members Meeting at Rounday Pavillion Golf Club, Rawmarsh
		</h3>
		

<p>Details to follow.</p>

<p>&nbsp;</p>

<p>&nbsp;</p><hr /></div> 
			</td>
		</tr>
	</table>
	
</div>
<!-- footer -->

	<table width="95%"><tr>
 		<td valign="middle" bgcolor="#FFFFFF" height="30"><div align="center" class="copyright">Copyright
    	© 2002 Sheffield and District Landlord Association  |  Site by <a
    	href="http://www.novate.co.uk" target="_blank" class="subtitle">Novate</a>
    	</div></td>
  	</tr>
	</table>
</table>
</body>
</html>