

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 09/02/2004 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>SADLA - Links Page </title>
<meta name="description" content="">
<meta name="keywords" content="">
<!-- start of header file -->

<script language="javascript" src="includes/default_javascript.js" type="text/javascript"></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<link href="/forum/includes/default_style.css" rel="stylesheet" type="text/css" />

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--jAVA FOR NAVE CELL COLOR CHANGE -->
<script language="Javascript"> 
	<!-- 
	function inCell(cell, newcolor) { 
		cell.bgColor = newcolor; 
	} 

	function outCell(cell, newcolor) { 
		cell.bgColor = newcolor;
	} 
	
	function go(loc) {
		window.location.href = loc;
	}
//  End -->
</script>


	<style>
		#popwindow { display: none;	}
	</style>


</head>


<!-- no popout -->
		<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#ffffff">

<table cellspacing="0" cellpadding="0" border="0" width="100%"><tr>
	<td width="136" style="background:#009cf0; margin:10px; padding-top:10px;" valign="top">
	<div align="center"><img src="/images/sadlaLogo.gif" width="82" height="135" border="0" alt=""></div>
		<br />
<div id=navvy>
<table class="tooltext1" cellspacing="0" cellpadding="0" style="border:0px;">
	<tr>

  
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('default.asp')" height="27"> 
  &nbsp;Home
  </TD></tr><tr>
	
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('benefits.asp')" height="27"> 
  &nbsp;Membership&nbsp;Benefits
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('events.asp')" height="27"> 
  &nbsp;Events
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#999999" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#999999');" onclick="go('links.asp')" height="27"> 
  &nbsp;Links
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('constitution.asp')" height="27"> 
	&nbsp;Constitution
	</TD></tr><tr>
	
<!-- 	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('news.asp')" height="27"> 
	&nbsp;News
	</TD></tr><tr> -->
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/members/member-home.asp')" height="27"> 
  &nbsp;Member Area
  </TD></tr><tr>
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/forum/')" height="27"> 
  &nbsp;Forum
  </TD></tr><tr>
  
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('join.asp')" height="27"> 
  &nbsp;Join
  </TD></tr><tr>	
			
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('contact.asp')" height="27"> 
  &nbsp;Contact&nbsp;us
	</TD></tr><tr>
		
	<!-- closing cell -->
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#009cf0" WIDTH="153" height="27">&nbsp;
	
	</TD></tr>
  </table>
</div>  <!-- end of navvy -->	 
<!-- End of menu table -->

</td>
	<td valign="top">
	
	<!-- its a table to just hold the banner -->
		<table width="100%" border="0" cellspacing="0" cellpadding="0" height="30">
      <tr bgcolor="#009CF0">
       	  <td height="30"> 
         	  <div align="center"><img src="/Images/slogan2.gif" width="486" height="25"
           	alt="Sheffield District and Landlord Association" align="middle"> </div>
         	</td>
      </tr>
    </table>
		
			<img src="../images/corner.gif" width="25" height="20" border="0" alt="">	
			
<!-- end of header file -->

<center>
        <table width="80%" border="0" cellspacing="0" cellpadding="10">
          <tr> 
            <td> <p class="title"> Links</p></td>
          </tr>
          <tr> 
            <td> <a href="http://www.landlords.org.uk/" target="_blank">National Landlords Association
              </a> (NLA).  <img src="/images/exlink.gif"></td>
          </tr>
          <tr> 
            <td> <a href="http://www.nfrl.org.uk/" target="_blank">National Federation 
              of Residential Landlords</a> (NFRL).  <img src="/images/exlink.gif"></td>
          </tr>
          <tr> 
            <td><a href="landlord_student_accommodation_advice_uk.htm">Accommodationforstudents.com</a> 
              <table border='0' width='54%' cellspacing='0' cellpadding='0' height='100%'>
                <tr> 
                  <td width='100%' bgcolor='#CE965A' height='60'> <p align='center'><font face='Verdana'> 
                      <a target="_blank" href="http://www.accommodationforstudents.com"> 
                      <img border='0' src='Images/afs_logo_180_30_2.gif' width='180' height='60'></a></font></td>
                </tr>
                <tr> 
                  <td width='100%' bgcolor='#CE965A' align='center' height='32'><b> 
                    <font face="Verdana" style="font-size: 14px" color="#FFFFFF"> 
                    <a href="landlord_student_accommodation_advice_uk.htm"> <font color="#FFFFFF">Click 
                    here to find out how to advertise your properties to students 
                    and professionals</font></a></font></b></td>
                </tr>
              </table></td>
          </tr>
          <tr> 
            <td><a href="http://www.studentlandlord.org.uk" target="_blank">Studentlandlord.org.uk</a> <img src="/images/exlink.gif"></td>
          </tr>
          <tr> 
            <td><a href="http://www.landlordlaw.co.uk" target="_blank">Landlordlaw.co.uk</a> <img src="/images/exlink.gif"></td>
          </tr>
          <tr>
            <td><a href="http://www.alanboswell.co.uk/landlords_insurance/associations_profile.aspx?id=DE05I31H">Alan 
              Boswells</a> <img src="/images/exlink.gif"></td>
          </tr>
		  <tr>
            <td><a href="http://www.letcheck.co.uk" target="_blank">www.letcheck.co.uk</a> <img src="/images/exlink.gif"></td>
          </tr>
  		  <tr>
            <td><a href="http://www.landlord-forum.co.uk" target="_blank">www.landlord-forum.co.uk </a><img src="/images/exlink.gif"></td>
          </tr>
          <tr> 
            <td><a href="http://www.residentiallandlord.co.uk" target="_blank">www.residentiallandlord.co.uk</a> <img src="/images/exlink.gif"></td>
          </tr>
        </table>
</center>
<!-- footer -->

	<table width="95%"><tr>
 		<td valign="middle" bgcolor="#FFFFFF" height="30"><div align="center" class="copyright">Copyright
    	© 2002 Sheffield and District Landlord Association  |  Site by <a
    	href="http://www.novate.co.uk" target="_blank" class="subtitle">Novate</a>
    	</div></td>
  	</tr>
	</table>
</table>
</body>
</html>