

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 09/02/2004 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>SADLA - News</title>
<meta name="description" content="">
<meta name="keywords" content="">
<!-- start of header file -->

<script language="javascript" src="includes/default_javascript.js" type="text/javascript"></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<link href="/forum/includes/default_style.css" rel="stylesheet" type="text/css" />

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--jAVA FOR NAVE CELL COLOR CHANGE -->
<script language="Javascript"> 
	<!-- 
	function inCell(cell, newcolor) { 
		cell.bgColor = newcolor; 
	} 

	function outCell(cell, newcolor) { 
		cell.bgColor = newcolor;
	} 
	
	function go(loc) {
		window.location.href = loc;
	}
//  End -->
</script>


	<style>
		#popwindow { display: none;	}
	</style>


</head>


<!-- no popout -->
		<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#ffffff">

<table cellspacing="0" cellpadding="0" border="0" width="100%"><tr>
	<td width="136" style="background:#009cf0; margin:10px; padding-top:10px;" valign="top">
	<div align="center"><img src="/images/sadlaLogo.gif" width="82" height="135" border="0" alt=""></div>
		<br />
<div id=navvy>
<table class="tooltext1" cellspacing="0" cellpadding="0" style="border:0px;">
	<tr>

  
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('default.asp')" height="27"> 
  &nbsp;Home
  </TD></tr><tr>
	
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('benefits.asp')" height="27"> 
  &nbsp;Membership&nbsp;Benefits
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('events.asp')" height="27"> 
  &nbsp;Events
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('links.asp')" height="27"> 
  &nbsp;Links
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('constitution.asp')" height="27"> 
	&nbsp;Constitution
	</TD></tr><tr>
	
<!-- 	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#999999" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#999999');" onclick="go('news.asp')" height="27"> 
	&nbsp;News
	</TD></tr><tr> -->
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/members/member-home.asp')" height="27"> 
  &nbsp;Member Area
  </TD></tr><tr>
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/forum/')" height="27"> 
  &nbsp;Forum
  </TD></tr><tr>
  
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('join.asp')" height="27"> 
  &nbsp;Join
  </TD></tr><tr>	
			
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('contact.asp')" height="27"> 
  &nbsp;Contact&nbsp;us
	</TD></tr><tr>
		
	<!-- closing cell -->
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#009cf0" WIDTH="153" height="27">&nbsp;
	
	</TD></tr>
  </table>
</div>  <!-- end of navvy -->	 
<!-- End of menu table -->

</td>
	<td valign="top">
	
	<!-- its a table to just hold the banner -->
		<table width="100%" border="0" cellspacing="0" cellpadding="0" height="30">
      <tr bgcolor="#009CF0">
       	  <td height="30"> 
         	  <div align="center"><img src="/Images/slogan2.gif" width="486" height="25"
           	alt="Sheffield District and Landlord Association" align="middle"> </div>
         	</td>
      </tr>
    </table>
		
			<img src="../images/corner.gif" width="25" height="20" border="0" alt="">	
			
<!-- end of header file -->

<table width="95%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td>&nbsp;</td>
          <td width="200" class="subtitle">&nbsp;</td>
        </tr>
        <tr> 
          <td><table width="100%" border="0" cellspacing="0" cellpadding="10">
              <tr>
                <td width="1%">&nbsp;</td>
                <td><p class="title">Recent News</p></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                               
                <td class="text"><span class="tiHeading"><strong><a name="news1"></a>Wash 
                  Hand Basin Update</strong></span> 
                  <p>To: All 
                    NFRL Affiliated Associations<br>
                    <br>
                    From: Mike Stimpson <br>
                    <br>
                    Date: 5th April 2007 <br>
                    <br>
                    <br>
                    <br>
                    NFRL &#8211; Acting nationally for local landlords<br>
                    <br>
                    <br>
                    <br>
                    WASH HAND BASINS<br>
                    <br>
                    Member associations will be aware that included within the 
                    secondary legislation of the 2004 Housing Act is the requirement 
                    to provide wash hand basins in all bedrooms where there are 
                    5 or more occupants in the property. <br>
                    <br>
                    The legislation came from the old HMO regulations, where it 
                    was a requirement to provide washing facilities in all living 
                    rooms in non self-contained accommodation within Houses in 
                    Multiple Occupation. The only concession made between the 
                    new legislation and the old is that the regulations only apply 
                    where there are 5 or more occupants, which is mainly within 
                    shared housing.<br>
                    <br>
                    As the regulations, in effect, already existed, no consultation 
                    was carried out and it was not until the effect of the regulations, 
                    particularly upon shared housing, was realised that representations 
                    were made. By this time, the secondary legislation had already 
                    been passed and Communities and Local Government (CLG) inferred 
                    that Government had &#8216;no appetite for change&#8217; at 
                    this early stage of licensing. Nevertheless, CLG and the IDeA 
                    (Improvement and Development Agency) websites received more 
                    comments from landlords, landlords&#8217; associations, tenants&#8217; 
                    organisations and local authorities regarding the hand basin 
                    requirements than any other single matter. <br>
                    <br>
                    NFRL, of course, made representations and also brought up 
                    this issue as a matter of urgent concern with LACORS, who 
                    have been engaged to monitor and report on the effect of licensing. 
                    The result, so far, is that most local authorities accept 
                    that the requirement in many cases is unreasonable. Tenants&#8217; 
                    organisations and many tenants themselves also consider the 
                    requirement &#8216;over the top&#8217;. A special debate was 
                    held in parliament but the Housing Spokesman, Baroness Andrews, 
                    made it clear that so far as Government was concerned the 
                    requirement was good practice and should not be changed. <br>
                    <br>
                    The current situation is that most local authorities are giving 
                    very extended periods for landlords to comply with the wash 
                    hand basin regulations when issuing licences. Namely, up to 
                    5 years, i.e. the period of the licence, as they believe, 
                    as NFRL does, that CLG will recommend an amendment to the 
                    Act to make such provision discretionary and not compulsory. 
                    <br>
                    <br>
                    Local associations should therefore negotiate with their respective 
                    local authorities for a long lead in period in which the wash 
                    hand basin regulation should be implemented as a condition 
                    of licensing. In the meantime, NFRL, together with its partners, 
                    will seek to ensure speedy change of the regulation. <br>
                    <br>
                    Any local association having difficulty in persuading its 
                    local authorities to give lengthy implementation periods should 
                    notify NFRL, with clear details of the local authority requirements. 
                    <br>
                    <br>
                    SHEFFIELD HAS ALREADY AGREED TO A 5-YEAR TIMESCALE SO NO WORRIES 
                    ON THAT SCORE FOR ANYONE.<br>
                    <br>
                    Mike Stimpson<br>
                    President<br>
                    NFRL </p>
                  <p></p>
                  <p><br>
                  </p>
                  <p><a href="/news4.asp">Next News</a></p>
                  </td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
            </table></td>
          <td width="200" valign="top"> <table width="200" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="tiText">&nbsp;</td>
              </tr>
              <tr> 
                <td height="13" align="left" class="tiText">&nbsp;</td>
              </tr>
            </table>
            <table width="200" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="tiText">&nbsp;</td>
              </tr>
              <tr> 
                <td height="13" align="left" class="tiText">&nbsp;</td>
              </tr>
            </table>
            <br>
          </td>
        </tr>
      </table>

<!-- footer -->

	<table width="95%"><tr>
 		<td valign="middle" bgcolor="#FFFFFF" height="30"><div align="center" class="copyright">Copyright
    	© 2002 Sheffield and District Landlord Association  |  Site by <a
    	href="http://www.novate.co.uk" target="_blank" class="subtitle">Novate</a>
    	</div></td>
  	</tr>
	</table>
</table>
</body>
</html>