

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 09/02/2004 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>SADLA - News</title>
<meta name="description" content="">
<meta name="keywords" content="">
<!-- start of header file -->

<script language="javascript" src="includes/default_javascript.js" type="text/javascript"></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<link href="/forum/includes/default_style.css" rel="stylesheet" type="text/css" />

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--jAVA FOR NAVE CELL COLOR CHANGE -->
<script language="Javascript"> 
	<!-- 
	function inCell(cell, newcolor) { 
		cell.bgColor = newcolor; 
	} 

	function outCell(cell, newcolor) { 
		cell.bgColor = newcolor;
	} 
	
	function go(loc) {
		window.location.href = loc;
	}
//  End -->
</script>


	<style>
	<!-- Start of tags for the pop-out advert - when not enabled -->
	#winDisplay {
	 display: none;
	}
	</style>


</head>


<!-- no popout -->
		<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#ffffff">

<table cellspacing="0" cellpadding="0" border="0" width="100%"><tr>
	<td width="136" style="background:#009cf0; margin:10px; padding-top:10px;" valign="top">
	<div align="center"><img src="/images/sadlaLogo.gif" width="82" height="135" border="0" alt=""></div>
		<br />
<div id=navvy>
<table class="tooltext1" cellspacing="0" cellpadding="0" style="border:0px;">
	<tr>

  
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('default.asp')" height="27"> 
  &nbsp;Home
  </TD></tr><tr>
	
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('benefits.asp')" height="27"> 
  &nbsp;Membership&nbsp;Benefits
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('events.asp')" height="27"> 
  &nbsp;Events
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('links.asp')" height="27"> 
  &nbsp;Links
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('constitution.asp')" height="27"> 
	&nbsp;Constitution
	</TD></tr><tr>
	
<!-- 	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#999999" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#999999');" onclick="go('news.asp')" height="27"> 
	&nbsp;News
	</TD></tr><tr> -->
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/members/member-home.asp')" height="27"> 
  &nbsp;Member Area
  </TD></tr><tr>
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/forum/')" height="27"> 
  &nbsp;Forum
  </TD></tr><tr>
  
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('join.asp')" height="27"> 
  &nbsp;Join
  </TD></tr><tr>	
			
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('contact.asp')" height="27"> 
  &nbsp;Contact&nbsp;us
	</TD></tr><tr>
		
	<!-- closing cell -->
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#009cf0" WIDTH="153" height="27">&nbsp;
	
	</TD></tr>
  </table>
</div>  <!-- end of navvy -->	 
<!-- End of menu table -->

</td>
	<td valign="top">
	
	<!-- its a table to just hold the banner -->
		<table width="100%" border="0" cellspacing="0" cellpadding="0" height="30">
      <tr bgcolor="#009CF0">
       	  <td height="30"> 
         	  <div align="center"><img src="/Images/slogan2.gif" width="486" height="25"
           	alt="Sheffield District and Landlord Association" align="middle"> </div>
         	</td>
      </tr>
    </table>
		
			<img src="../images/corner.gif" width="25" height="20" border="0" alt="">	
			
<!-- end of header file -->


<table width="95%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td>&nbsp;</td>
          <td width="200" class="subtitle">&nbsp;</td>
        </tr>
        <tr> 
          <td><table width="100%" border="0" cellspacing="0" cellpadding="10">
              <tr>
                <td width="1%">&nbsp;</td>
                <td><p class="title">Recent News</p></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                               
                <td class="text"><span class="tiHeading"><a name="news1"></a></span><strong>The ammenity standards is still draft only and is being reviewed by Sheffield 
                  Council</strong> <p>At a meeting with Sheffield City Council on 9th August it was agreed that the Sheffield Amenity   Standards as displayed on the Sheffield City Council website would be   withdrawn with immediate effect and a rider be inserted to inform all viewers   that this is a draft proposal for discussion &amp; comments from all interested   parties.</p>
                  <p>The closing date for accepting comments is <STRONG>11 September 2007</STRONG>. Comments should be made to Sadla in writing or by email. </p>
                  <p>A copy of this document is detailed below.</p>
                  <p><a href="members/HMO Standards version 5[1].doc">HMO standards version 5.doc</a> </p>
                  <p><br>
                  </p>
                  <p><br>
                  </p>
                  <p>&nbsp;</p>
  		          <p><a href="/news2.asp">Next News</a></p>

                </td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
            </table></td>
          <td width="200" valign="top"> <table width="200" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="tiText">&nbsp;</td>
              </tr>
              <tr> 
                <td height="13" align="left" class="tiText">&nbsp;</td>
              </tr>
            </table>
            <table width="200" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="tiText">&nbsp;</td>
              </tr>
              <tr> 
                <td height="13" align="left" class="tiText">&nbsp;</td>
              </tr>
            </table>
            <br>
          </td>
        </tr>
      </table>

<!-- footer -->

	<table width="95%"><tr>
 		<td valign="middle" bgcolor="#FFFFFF" height="30"><div align="center" class="copyright">Copyright
    	© 2002 Sheffield and District Landlord Association  |  Site by <a
    	href="http://www.novate.co.uk" target="_blank" class="subtitle">Novate</a>
    	</div></td>
  	</tr>
	</table>
</table>
</body>
</html>