

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 09/02/2004 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>SADLA - News</title>
<meta name="description" content="">
<meta name="keywords" content="">
<!-- start of header file -->

<script language="javascript" src="includes/default_javascript.js" type="text/javascript"></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<link href="/forum/includes/default_style.css" rel="stylesheet" type="text/css" />

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--jAVA FOR NAVE CELL COLOR CHANGE -->
<script language="Javascript"> 
	<!-- 
	function inCell(cell, newcolor) { 
		cell.bgColor = newcolor; 
	} 

	function outCell(cell, newcolor) { 
		cell.bgColor = newcolor;
	} 
	
	function go(loc) {
		window.location.href = loc;
	}
//  End -->
</script>


	<style>
	<!-- Start of tags for the pop-out advert - when not enabled -->
	#winDisplay {
	 display: none;
	}
	</style>


</head>


<!-- no popout -->
		<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#ffffff">

<table cellspacing="0" cellpadding="0" border="0" width="100%"><tr>
	<td width="136" style="background:#009cf0; margin:10px; padding-top:10px;" valign="top">
	<div align="center"><img src="/images/sadlaLogo.gif" width="82" height="135" border="0" alt=""></div>
		<br />
<div id=navvy>
<table class="tooltext1" cellspacing="0" cellpadding="0" style="border:0px;">
	<tr>

  
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('default.asp')" height="27"> 
  &nbsp;Home
  </TD></tr><tr>
	
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('benefits.asp')" height="27"> 
  &nbsp;Membership&nbsp;Benefits
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('events.asp')" height="27"> 
  &nbsp;Events
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('links.asp')" height="27"> 
  &nbsp;Links
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('constitution.asp')" height="27"> 
	&nbsp;Constitution
	</TD></tr><tr>
	
<!-- 	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#999999" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#999999');" onclick="go('news.asp')" height="27"> 
	&nbsp;News
	</TD></tr><tr> -->
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/members/member-home.asp')" height="27"> 
  &nbsp;Member Area
  </TD></tr><tr>
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/forum/')" height="27"> 
  &nbsp;Forum
  </TD></tr><tr>
  
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('join.asp')" height="27"> 
  &nbsp;Join
  </TD></tr><tr>	
			
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('contact.asp')" height="27"> 
  &nbsp;Contact&nbsp;us
	</TD></tr><tr>
		
	<!-- closing cell -->
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#009cf0" WIDTH="153" height="27">&nbsp;
	
	</TD></tr>
  </table>
</div>  <!-- end of navvy -->	 
<!-- End of menu table -->

</td>
	<td valign="top">
	
	<!-- its a table to just hold the banner -->
		<table width="100%" border="0" cellspacing="0" cellpadding="0" height="30">
      <tr bgcolor="#009CF0">
       	  <td height="30"> 
         	  <div align="center"><img src="/Images/slogan2.gif" width="486" height="25"
           	alt="Sheffield District and Landlord Association" align="middle"> </div>
         	</td>
      </tr>
    </table>
		
			<img src="../images/corner.gif" width="25" height="20" border="0" alt="">	
			
<!-- end of header file -->


<table width="95%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td>&nbsp;</td>
          <td width="200" class="subtitle">&nbsp;</td>
        </tr>
        <tr> 
          <td><table width="100%" border="0" cellspacing="0" cellpadding="10">
              <tr>
                <td width="1%">&nbsp;</td>
                <td><p class="title">&nbsp;</p></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                               
                <td class="text"><span class="tiHeading"><a name="news1"></a></span><strong>AGM-Wednesday, 
                  9th. May, 2007, South Yorks Police Sports &amp; Social Club, 
                  Niagara Road Sheffield.S6 1LU, 6.30-9pm.,approx..</strong>
<p>Our AGM will be held on Wednesday, 9th.May, 2007. We are 
                    proposing that the SADLA Committee stands as is, since the 
                    SADLA Committee all wish to serve a further year in office. 
                    Owing to time constraints because of your SADLA Committee 
                    spending a considerable amount of time dealing with the administration 
                    of The Tenancy Deposit Scheme &amp; the Introduction of the 
                    Regulatory Reform (Fire Safety) Order 2005 being still ongoing 
                    the SADLA Committee has no proposals as a proposition to put 
                    to the AGM at this stage, no voting will, therefore, be needed 
                    on any such matters.<br>
                    In the near future should any resolutions be forthcoming then 
                    these can easily be dealt within the framework of an EGM.</p>
                  <p>SADLA Members who attended the recent Forum for University 
                    Registered Landlords/Ladies: Monday 16th. April, 2007 hosted 
                    by The University of Sheffield Accommodation &amp; Campus 
                    Services will be aware of the ongoing situation with regard 
                    to the Regulatory Reform (Fire Safety) Order 2005 &amp; the 
                    stance currently being taken by South Yorkshire Fire &amp; 
                    Rescue Service. SADLA wishes to bring every member up to date 
                    with the current situation &amp; the actions being taken by 
                    SADLA &amp; other interested parties both locally &amp; nationally 
                    to protect every member from having to make additional adaptations 
                    to their properties. Please make very effort to attend to 
                    support your SADLA Committee in their efforts to arrive at 
                    a way forward for the benefit of all landlords.<br>
                    Please find enclosed a copy of the minutes of the last SADLA 
                    AGM. The SADLA Committee look forward to meeting you there.</p>
                  <p>Yours sincerely,</p>
                  <p><br>
                    S. Simcock.<br>
                    Secretary.<br>
                  </p>
                  <p><a href="members/SADLA%20AGM%20Agenda%20Fire%20Issues.doc">AGM 
                    and reply form</a></p>
                  <p> </p>
                  <p>&nbsp;</p>
		          <p><a href="/news1.asp">Next News</a></p>
                  </td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
            </table></td>
          <td width="200" valign="top"> <table width="200" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="tiText">&nbsp;</td>
              </tr>
              <tr> 
                <td height="13" align="left" class="tiText">&nbsp;</td>
              </tr>
            </table>
            <table width="200" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="tiText">&nbsp;</td>
              </tr>
              <tr> 
                <td height="13" align="left" class="tiText">&nbsp;</td>
              </tr>
            </table>
            <br>
          </td>
        </tr>
      </table>


<!-- footer -->

	<table width="95%"><tr>
 		<td valign="middle" bgcolor="#FFFFFF" height="30"><div align="center" class="copyright">Copyright
    	© 2002 Sheffield and District Landlord Association  |  Site by <a
    	href="http://www.novate.co.uk" target="_blank" class="subtitle">Novate</a>
    	</div></td>
  	</tr>
	</table>
</table>
</body>
</html>