

<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 09/02/2004 -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>SADLA - </title>
<meta name="description" content="">
<meta name="keywords" content="">
<!-- start of header file -->

<script language="javascript" src="includes/default_javascript.js" type="text/javascript"></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<link href="/forum/includes/default_style.css" rel="stylesheet" type="text/css" />

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--jAVA FOR NAVE CELL COLOR CHANGE -->
<script language="Javascript"> 
	<!-- 
	function inCell(cell, newcolor) { 
		if (!cell.contains(event.fromElement)) { 
		cell.bgColor = newcolor; 
		} 
	} 

	function outCell(cell, newcolor) { 
		if (!cell.contains(event.toElement)) { 
		cell.bgColor = newcolor;
		} 
	} 
	
	function go(loc) {
		window.location.href = loc;
	}
//  End -->
</script>



</head>


<!-- no popout -->
		<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#ffffff">

<table cellspacing="0" cellpadding="0" border="0" width="100%"><tr>
	<td width="136" style="background:#009cf0; margin:10px; padding-top:10px;" valign="top">
	<div align="center"><img src="/images/sadlaLogo.gif" width="82" height="135" border="0" alt=""></div>
		<br />
<div id=navvy>
<table class="tooltext1" cellspacing="0" cellpadding="0" style="border:0px;">
	<tr>

  
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('default.asp')" height="27"> 
  &nbsp;Home
  </TD></tr><tr>
	
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('benefits.asp')" height="27"> 
  &nbsp;Membership&nbsp;Benefits
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('events.asp')" height="27"> 
  &nbsp;Events
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('links.asp')" height="27"> 
  &nbsp;Links
  </TD></tr><tr>

	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('constitution.asp')" height="27"> 
	&nbsp;Constitution
	</TD></tr><tr>
	
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('news.asp')" height="27"> 
	&nbsp;News
	</TD></tr><tr>
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/members/member-home.asp')" height="27"> 
  &nbsp;Member Area
  </TD></tr><tr>
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/forum/')" height="27"> 
  &nbsp;Forum
  </TD></tr><tr>
  
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('join.asp')" height="27"> 
  &nbsp;Join
  </TD></tr><tr>	
			
	
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('contact.asp')" height="27"> 
  &nbsp;Contact&nbsp;us
	</TD></tr><tr>
		
	<!-- closing cell -->
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#009cf0" WIDTH="153" height="27">&nbsp;
	
	</TD></tr>
  </table>
</div>  <!-- end of navvy -->	 
<!-- End of menu table -->

</td>
	<td valign="top">
	
	<!-- its a table to just hold the banner -->
		<table width="100%" border="0" cellspacing="0" cellpadding="0" height="30">
      <tr bgcolor="#009CF0">
       	  <td height="30"> 
         	  <div align="center"><img src="/Images/slogan2.gif" width="486" height="25"
           	alt="Sheffield District and Landlord Association" align="middle"> </div>
         	</td>
      </tr>
    </table>
		
			<img src="../images/corner.gif" width="25" height="20" border="0" alt="">	
			
<!-- end of header file -->

<table width="95%" border="0" cellspacing="0" cellpadding="0">
        <tr> 
          <td>&nbsp;</td>
          <td width="200" class="subtitle">&nbsp;</td>
        </tr>
        <tr> 
          <td><table width="100%" border="0" cellspacing="0" cellpadding="10">
              <tr>
                <td width="1%">&nbsp;</td>
                <td><p class="title">Recent News</p></td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                               
                <td class="text"><span class="tiHeading"><strong>Sadla's 
                  recommended statement when filling in the Sheffield Councils 
                  HMO application</a></strong></span> 
                  <p> <br>
                    9th. June, 2006 </p>
                  <p><br>
                    Dear Members,<br>
                    <br>
                    Application for Mandatory Licensing of Houses in Multiple 
                    Occupation.</p>
                  <p>Several landlords have raised concerns about the personal 
                    liability associated with signing certain declarations contained 
                    on the application form-especially Part 3-Information about 
                    the Property.</p>
                  <p>As your SADLA Committee we propose to seek legal advice on 
                    this. As time is short before the deadline of July 5th.2006, 
                    we are suggesting, in the meantime, to you that the following 
                    statements are inserted in the application form, in order 
                    to cover yourself against being guilty of signing declarations, 
                    that may be reckless, false or misleading.<br>
                    PART 3-INFORMATION ABOUT THE PROPERTY.</p>
                  <p>Section 3.13. Fire Safety Training-Insert NONE.</p>
                  <p>Section 3.19. Gas Installation &amp; Appliances. Please add 
                    this addendum.<br>
                    Landlords are not trained &amp; qualified or Corgi-registered 
                    &amp;, therefore, cannot declare that the gas installation 
                    &amp; appliances in an HMO meet safety requirements. Also 
                    it is not possible or a requirement of the Law that gas appliances 
                    comply with any enactment. The Local Authority must specify 
                    specifically which enactment they are supposed to comply with 
                    in accordance with the Law. The qualified technician can only 
                    certify that the installation present in the property complies 
                    with the legal requirements under the Gas Safety (Installation 
                    &amp; Use Regulations (1998)), needed to issue a Gas-safety 
                    Certificate. Regulations &amp; enactments change constantly 
                    &amp;, therefore, in the case of an existing installation 
                    it will have complied with the regulations at the time of 
                    installation &amp; also comply with the relevant regulations 
                    in order for the gas safety certificate to be issued, but 
                    may not necessarily comply with all the latest regulations 
                    &amp; enactments but still be perfectly legal. For a landlord 
                    to sign the declaration in its current form would be to recklessly 
                    make a false &amp; misleading statement for which they could 
                    be held criminally liable. <br>
                    Landlords should declare that they have in their possession 
                    a current Landlord Gas Safety Certificate for all gas appliances 
                    in the property in accordance with the law issued by a competent 
                    Corgi-registered technician.</p>
                  <p>Section 3.20. Insert &#8220;I declare that the furniture 
                    &amp; furnishings in the property supplied by myself in the 
                    course of my trade or profession comply with the requirements 
                    of the current Furniture &amp; Furnishings (Fire)(Safety)Regulations1988, 
                    as amended 1989/1993). However, I have no control over furnishings 
                    that may be brought into the property by Third Parties &amp; 
                    which may not be covered by the act.&#8221;<br>
                    At the end of the document please add:<br>
                    &#8220;This declaration has been altered because to sign the 
                    declaration as drafted on this form I/we would be in breach 
                    of our duty not to be reckless as to whether a statement is 
                    false or misleading. In the form as set out I/we am/are unable 
                    to control every item of furniture or furnishing that is brought 
                    into the property &amp; under the terms of the act are not 
                    legally entitled to do so.&#8221;<br>
                    For anyone who has already completed &amp; returned their 
                    form(s) we suggest that they write to Sheffield City Council 
                    with the following addendum:<br>
                    &#8220;Following information received I/we am/are concerned 
                    that some of the declarations made on the Mandatory Licensing 
                    Application Form submitted may be inaccurate &amp;, therefore, 
                    I/we should like to add the following caveats. Then write 
                    out Sections 3.13, 3.19, &amp; 3.20. We shall try to keep 
                    you informed of any further developments etc..<br>
                    <br>
                    Yours sincerely,</p>
                  <p> Your SADLA Committee<br>
                  </p>
                  <p><br>
                  </p>
                  <p><br>
                  </p>
                  <p>&nbsp;</p>
                  <p>&nbsp;</p>
                  </td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
              <tr>
                <td>&nbsp;</td>
                
                <td class="tiHeading">&nbsp;</td>
              </tr>
            </table></td>
          <td width="200" valign="top"> <table width="200" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="tiText">&nbsp;</td>
              </tr>
              <tr> 
                <td height="13" align="left" class="tiText">&nbsp;</td>
              </tr>
            </table>
            <table width="200" border="0" cellspacing="0" cellpadding="0">
              <tr> 
                <td class="tiText">&nbsp;</td>
              </tr>
              <tr> 
                <td height="13" align="left" class="tiText">&nbsp;</td>
              </tr>
            </table>
            <br>
          </td>
        </tr>
      </table>

<!-- footer -->

	<table width="95%"><tr>
 		<td valign="middle" bgcolor="#FFFFFF" height="30"><div align="center" class="copyright">Copyright
    	© 2002 Sheffield and District Landlord Association  |  Site by <a
    	href="http://www.novate.co.uk" target="_blank" class="subtitle">Novate</a>
    	</div></td>
  	</tr>
	</table>
</table>
</body>
</html>