<html>
<!-- Generated by AceHTML Freeware http://freeware.acehtml.com -->
<!-- Creation date: 31/01/2004 -->
<head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<title></title>
<meta name="description" content="">
<meta name="keywords" content="">
<meta name="author" content="acehtml@snapey.co.uk">
<meta name="generator" content="AceHTML 5 Freeware">

<link href="/forum/includes/default_style.css" rel="stylesheet" type="text/css" />

<script  language="JavaScript">
<!-- Hide from older browsers...
//Function to open pop up window
function openWin(theURL,winName,features) {
  	window.open(theURL,winName,features);
}
// -->
</script>

<!-- start of header file -->
<script language="javascript" src="includes/default_javascript.js" type="text/javascript"></script>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

<link href="/forum/includes/default_style.css" rel="stylesheet" type="text/css" />

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<!--jAVA FOR NAVE CELL COLOR CHANGE -->
<script language="Javascript"> 
	<!-- 
	function inCell(cell, newcolor) { 
		if (!cell.contains(event.fromElement)) { 
		cell.bgColor = newcolor; 
		} 
	} 

	function outCell(cell, newcolor) { 
		if (!cell.contains(event.toElement)) { 
		cell.bgColor = newcolor;
		} 
	} 
	
	function go(loc) {
		window.location.href = loc;
	}
//  End -->
</script>

</head>

<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" bgcolor="#ffffff">
<table cellspacing="0" cellpadding="0" border="0" width="100%"><tr>
	<td width="136" style="background:'#009cf0'; margin:'10px';" valign="top" style="padding-top:'10px';">
	<div align="center"><img src="/images/sadlaLogo.gif" width="82" height="135" border="0" alt=""></div>
		<br />
<div id=navvy>
<table class="tooltext1" cellspacing="0" cellpadding="0" style="border:0px;">
	<tr>
	
  <TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#6898d0" WIDTH="153" onmouseover="inCell(this, '#686868');" onmouseout="outCell(this, '#6898d0');" onclick="go('/default.asp')" height="27"> 
  &nbsp;<img src="\images\backarrow.gif">&nbsp;SADLA&nbsp;Home
  </TD></tr><tr>	
	
	<!-- closing cell -->
	<TD class="tooltext1" ALIGN="LEFT" BGCOLOR="#009cf0" WIDTH="153" height="27">
	&nbsp;
	</TD></tr>

  </table>
</div>  <!-- end of navvy -->	 
<!-- End of menu table -->

</td>
	<td valign="top">
	
	<!-- its a table to just hold the banner -->
		<table width="100%" border="0" cellspacing="0" cellpadding="0" height="30">
      <tr bgcolor="#009CF0">
       	  <td height="30"> 
         	  <div align="center"><img src="/Images/slogan2.gif" width="486" height="25"
           	alt="Sheffield District and Landlord Association" align="middle"> </div>
         	</td>
      </tr>
    </table>
		
			<img src="../images/corner.gif" width="25" height="20" border="0" alt="">	
			
<!-- end of header file -->
<!-- The navigation file -->
			
<span class="text"><h1 style="margin-left: 5px" align="center">
<font color="#009cf0">Restricted Page</font></h1>
<p style="margin-left: 5px" align="center">The page that you are trying to access is available 
to SADLA members only. <br>Please login using your Forum username and password. </p>
<div align="center">
	<table border="1" width="500" cellspacing="0" cellpadding="0" style="border: 1px solid #C0C0C0; padding: 5px" bordercolor="#C0C0C0" id="table1">
		<tr>
			<td>
			<span class="text">
			<h3 style="margin-left: 5px" align="center"><font color="#009cf0">Login</font></h3>
			<div align="center">
				<table id="table2"><tr>
					<td class="smText">
						<form method="post" name="frmLogin" action="/security/mts_login_user.asp?From=/members/member-list.asp">
							<p style="margin-left: 5px" align="center">Quick Login:	
						  <input type="text" size="10" name="name" class="smText" />
							&nbsp;&nbsp;&nbsp;Password: <input type="password" size="10" name="password" class="smText" />
							<input type="hidden" name="QUIK" value="true" />
						  <input type="hidden" name="NS" value="1" />
							<input type="hidden" name="sessionID" value="15274986" />
							<input type="submit" value="Go" class="smText" />
							</p>
						</form></td>
					</tr>
				</table>
			</div>
			</span>
			</td>
		</tr>
	</table>
</div>

<p style="margin-left: 5px" align="center"><a href="JavaScript:openWin('/forum/forgotten_password.asp','forgot_pass','toolbar=0,location=0,status=0,menubar=0,scrollbars=0,resizable=1,width=570,height=350');">Click here if you have forgotten your password</a></p>
<p style="margin-left: 5px" align="center"><a href="/Reminder.asp">Click here if you are a SADLA member but have forgotten your username.</a></p>
<p style="margin-left: 5px" align="center"><a href="/Register.asp">Click here if you are a SADLA member but have not yet joined the Forum.</a></p>
</span>
<!-- footer -->

	<table width="95%"><tr>
 		<td valign="middle" bgcolor="#FFFFFF" height="30"><div align="center" class="copyright">Copyright
    	© 2002 Sheffield and District Landlord Association  |  Site by <a
    	href="http://www.novate.co.uk" target="_blank" class="subtitle">Novate</a>
    	</div></td>
  	</tr>
	</table>
</table>
</body>
</html>